include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_classes_with_only_static_members: false
    sort_pub_dependencies: false
    sort_child_properties_last: true
    directives_ordering: true
