name: my_draw
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  intl: ^0.19.0
  intl_utils: ^2.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  mockito: ^5.4.5

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: S